export const routes = {
  MAIN: '/',
  APOD: '/apod',
  MAST: '/mast',
  AUTH: '/auth',
  INFOPAGE: '/infopage',
  PLANETS: '/planets',
  SOLARSYSTEM: '/solarsystem',
  SOLARSYSTEMINFO: '/solarsysteminfo',
  SUNINFO: '/suninfo',
  KUIPERBELTINFO: '/kuiperbeltinfo',
  VENUS: '/venus',
  EARTH: '/earth',
  MARS: '/mars',
  JUPITER: '/jupiter',
  SATURN: '/saturn',
  URANUS: '/uranus',
  NEPTUN: '/neptun',
  MARSROVERS: '/marsrovers',
  CHEMCAM: '/chemcam',
  FHAZ: '/fhaz',
  MAHLI: '/mahli',
};
